name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
    - name: Set up CMake
      uses: lukka/get-cmake@v3.21.2
    - name: Remove CMake cache
      run: rm -rf build
    - name: Configure CMake
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build
    - name: Run tests
      run: cd build && ctest
    - name: Check for GPU availability
      run: |
        if command -v nvidia-smi &> /dev/null
        then
          echo "GPU is available"
        else
          echo "GPU is not available"
        fi
    - name: Check for CUDA installation
      run: |
        if [ -d "/usr/local/cuda" ]
        then
          echo "CUDA is installed"
        else
          echo "CUDA is not installed"
        fi
